
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "week8samproject-dev"
s3_bucket = "file-upload-bucket-dev-904233109505"
s3_prefix = "week8samproject"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false
disable_rollback = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "week8samproject-prod"
s3_bucket = "file-upload-bucket-dev-904233109505"
s3_prefix = "week8samproject"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = false
disable_rollback = false
